# Generated by Django 4.2.5 on 2024-08-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='apk_file_path',
            field=models.FileField(blank=True, null=True, upload_to='apk_files/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
