# Generated by Django 4.2.5 on 2024-08-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_app_apk_file_path_alter_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='first_screen_screenshot_path',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AddField(
            model_name='app',
            name='screen_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='second_screen_screenshot_path',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AddField(
            model_name='app',
            name='ui_hierarchy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='video_recording_path',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
