# Generated by Django 4.2.5 on 2024-08-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_app_first_screen_screenshot_path_app_screen_changed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppiumTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_hierarchy', models.TextField()),
                ('screen_changed', models.BooleanField()),
                ('initial_screenshot', models.ImageField(upload_to='screenshots/')),
                ('subsequent_screenshot', models.ImageField(upload_to='screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='analyzer.app')),
            ],
        ),
    ]
