# Generated by Django 4.2.5 on 2024-08-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_appiumtestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='appiumtestresult',
            name='log',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
